ekf_global_node:
  ros__parameters:
    frequency: 10.0
    two_d_mode: true
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: map

    odom0: /odometry/filtered
    odom0_config: [true, true, false,
                   false, false, true,
                   false, false, false,
                   false, false, false,
                   false, false, false]

    odom1: /slam_toolbox/pose
    odom1_config: [true, true, false,
                   false, false, true,
                   false, false, false,
                   false, false, false,
                   false, false, false]

    publish_filtered_output: true
    publish_filtered_output_topic: /odometry/global
