<?xml version="1.0"?>

<robot name="msds" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Properties -->
  <xacro:include filename="properties.xacro" />
  <!-- Start GZ or Ignition depending on ROS 2 Version -->
  <xacro:arg name="is_ignition" default="false"/>
  <!-- Load Simulated or Real Hardware Interfaces -->
  <xacro:arg name="is_sim" default="true"/>
  <!-- Port -->
  <xacro:arg name="port" default="/dev/esp"/>
  <!-- Include Gazebo Parameters -->
  <xacro:include filename="msds_gazebo.xacro" />
  <!-- Include ros2_control Plugins -->
  <xacro:include filename="msds_ros2_control.xacro" />

  <!-- Base Footprint -->
  <link name="base_footprint"/>
  
  <!-- Chassis -->
  <link name="base_link">
    <!-- <inertial>
      <origin xyz="0.00010187428365774479 -3.2714989699580867e-05 0.05381730231142636" rpy="0 0 0"/>
      <mass value="8.2573504e-01"/>
      <inertia ixx="2.2124416e-02" ixy="-1.2294101e-04" ixz="3.4938785e-04"
            iyy="2.1193702e-02" iyz="-5.0120904e-05"
            izz="2.0064271e-02" />
    </inertial> -->
    <xacro:box_inertia m="5.0" l="${2*chassis_length}" w="${2*chassis_width}" h="${2*chassis_height}" 
                           xyz="0 0 ${chassis_height / 2.0}" rpy="0 0 0"/>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://msds_description/meshes/base_link.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="white"/>
    </visual>
    <!-- <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://msds_description/meshes/base_link.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision> -->
    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <origin xyz="0 0 ${chassis_height / 2}" rpy="0 0 0"/>
    </collision>
  </link>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link" />
    <origin xyz="0 0 0.081" rpy="0 0 1.5708"/>
  </joint>
  
  
  <link name="front_right_wheel_link">
    <xacro:cylinder_inertia m="0.24" r="${wheel_radius}" h="${wheel_width}" 
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
    <visual>
      <origin xyz="0.2058 0.1199 0.0341" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://msds_description/meshes/front_right_link.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
    </collision>
  </link>

  <joint name="front_right_wheel_joint" type="continuous">
    <origin xyz="-0.2058 -0.1199 -0.0341" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="front_right_wheel_link"/>
    <axis xyz="1 0 0" />
  </joint>

  <link name="front_left_wheel_link">
    <xacro:cylinder_inertia m="0.24" r="${wheel_radius}" h="${wheel_width}" 
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
    <visual>
      <origin xyz="-0.2058 0.1199 0.0341" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://msds_description/meshes/front_left_link.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
    </collision>
  </link>

  <joint name="front_left_wheel_joint" type="continuous">
    <origin xyz="0.2058 -0.1199 -0.0341" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="front_left_wheel_link"/>
    <axis xyz="1.0 0.0 -0.0"/>
  </joint>

  <link name="rear_right_wheel_link">
    <xacro:cylinder_inertia m="0.24" r="${wheel_radius}" h="${wheel_width}" 
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
    <visual>
      <origin xyz="0.2058 -0.1199 0.0341" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://msds_description/meshes/rear_right_link.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
    </collision>
  </link>

  <joint name="rear_right_wheel_joint" type="continuous">
    <origin xyz="-0.2058 0.1199 -0.0341" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="rear_right_wheel_link"/>
    <axis xyz="-1.0 0.0 -0.0"/>
  </joint>
  
  <link name="rear_left_wheel_link">
    <xacro:cylinder_inertia m="0.24" r="${wheel_radius}" h="${wheel_width}" 
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
    <visual>
      <origin xyz="-0.2058 -0.1199 0.0341" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://msds_description/meshes/rear_left_link.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
    </collision>
  </link>

  <joint name="rear_left_wheel_joint" type="continuous">
    <origin xyz="0.2058 0.1199 -0.0341" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="rear_left_wheel_link"/>
    <axis xyz="-1.0 0.0 0.0"/>
  </joint>



  <link name="imu_link">
    <inertial>
      <origin xyz="-0.020000000000000004 0.0 0.0009205607476635534" rpy="0 0 0"/>
      <mass value="0.010079400000000002"/>
      <inertia ixx="0.0" iyy="1e-06" izz="1e-06" ixy="-0.0" iyz="0.0" ixz="0.0"/>
    </inertial>
    <visual>
      <origin xyz="0.087 -0.055 -0.014" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://msds_description/meshes/imu_link.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark_grey"/>
    </visual>
    <collision>
      <origin xyz="0.107 -0.06 -0.014" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://msds_description/meshes/imu_link.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
  </link>
  
  <joint name="imu_joint" type="fixed">
    <origin xyz="-0.087 0.055 0.014" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="imu_link"/>
  </joint>
  
  <link name="laser_link">
    <inertial>
      <origin xyz="-0.05479577138899063 -0.007200165837721026 0.017999309133954644" rpy="0 0 0"/>
      <mass value="0.7855753539396106"/>
      <inertia ixx="0.000268" iyy="0.000268" izz="0.000331" ixy="-0.0" iyz="0.0" ixz="-0.0"/>
    </inertial>
    <visual>
      <origin xyz="-0.0 0.105 -0.08" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://msds_description/meshes/lidar_link.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark_grey"/>
    </visual>
    <collision>
      <origin xyz="-0.05 0.105 -0.08" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://msds_description/meshes/lidar_link.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
  </link>
  
  
  <joint name="laser_joint" type="fixed">
    <origin xyz="0.0 -0.105 0.08" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="laser_link"/>
  </joint>
  
</robot>
  