controller_manager:
  ros__parameters:
    update_rate: 100 # This means the controller will executed 100Hz i.e 10 times per second
    use_sim_time: false # Set to true if you are using simulation

    # Add the name of the controllers you want to load and use for your robot
    msds_controller:
      type: "mecanum_drive_controller/MecanumDriveController"

    joint_state_broadcaster: # Responsible for publishing the current state of each joint of the robot into the /joint_states topic
      type: joint_state_broadcaster/JointStateBroadcaster

    # simple_velocity_controller:
    #   type: velocity_controllers/JointGroupVelocityController



# This is the configuration for the mecanum_drive_controller
msds_controller:
  ros__parameters:
    reference_timeout: 5.0

    front_left_wheel_command_joint_name: "front_left_wheel_joint"
    front_right_wheel_command_joint_name: "front_right_wheel_joint"
    rear_right_wheel_command_joint_name: "rear_right_wheel_joint"
    rear_left_wheel_command_joint_name: "rear_left_wheel_joint"

    kinematics:
      base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
      wheels_radius: 0.0485
      sum_of_robot_center_projection_on_X_Y_axis: 0.7

    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    enable_odom_tf: true
    # pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    # twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]

    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.0, 0.0, 0.01]

# simple_velocity_controller:
#   ros__parameters:
#     joints:
#       - "front_left_wheel_joint"
#       - "front_right_wheel_joint"
#       - "rear_left_wheel_joint"
#       - "rear_right_wheel_joint"